@@startuml

start

:init();

:systemStart();

repeat
    if (start game?) then (yes)
        :startGame();
    else (no)
        :finishGame();
        break
    endif
repeat while (0)

end
@@enduml