@@startuml

title ゲームクリア後にタイトル画面に戻るまで

eventManager -> IOManager : waitInput()
    alt you got any kind of key input
        IOManager -> readKey : getInput()
        readKey --> IOManager
    end
IOManager --> eventManager

eventManager -> viewChanger : backToTitle()
    viewChanger -> IOManager : showTitle()
        IOManager -> showView : writeTitle()
        showView --> IOManager
    IOManager --> viewChanger
viewChanger --> eventManager

@@enduml