@startuml

title タイトル画面からの遷移

eventManager -> IOManager : waitInput()
    alt you got any kind of key input
        IOManager -> readKey : getInput()
        readKey --> IOManager
    end
IOManager --> eventManager

alt finish game
    eventManager -> viewChanger : finishGame()
        viewChanger -> IOManager : showFinishView()
            IOManager -> showView : writeFinishMessage()
            showView --> IOManager
        IOManager --> viewChanger
    viewChanger --> eventManager
    eventManager -> eventManager : endMyself()
    break
        note right
            end main loop
        end note
    end

else start game
    eventManager -> labyrinthManager : makeLabyrinth()
    labyrinthManager --> eventManager
    
    eventManager -> playerManager : makePlayer()
    playerManager -->eventManager

    eventManager -> timer : getTime()
    timer --> eventManager

    eventManager -> viewChanger : playGame()
        viewChanger -> IOManager : showGameView()
            IOManager -> showView : writeLabandPl()
            showView --> IOManager
        IOManager --> viewChanger
    viewChanger --> eventManager

    note right
        ゲームシーケンスへ
    end note

end


@enduml