@startuml

title ゲームプレイ時のアクティビティ図

start
    repeat
        if (not pass Labyrinth?) then (yes)
            :procGame();
        else (no)
            break
        endif
    repeat while (not pass game?)

    :calcPlayTime();
    :ProcAfterPassGame();

    :backToTitle();

end

@enduml