@startuml

title ゲーム開始

start

    :chooseLabyrinth();
    :setLabyrinth();
    :setPlayer();
    :setStartTime();

    repeat
        :playGame();
    repeat while (pass Game?)

@enduml