@startuml
title クラス図

class Player {
    -int[][] currentPosition
    +procPlayer()
    +getPositionOfPl()
}
class Labyrinth {
    -int     ID
    -int[2]  cordinateOfGoal
    -int[][] mapOfLabyrinth
    -int[][] revealedMpOfLabyrinth
    +makeLabyrinth()
    +isWallorWay()
    +revealMap()
    +getRevealedMap()
    +isPlayerOnGoal()
    +getAllIDOFLab();
}
class Message {
    +String congratuation
    +String endGame
    +String startGame
    +String Title
    +String onGamging
}
class Time {
    -int startTime
    +setStartTime()
    +calcPlayTime()
}


@enduml
