@startuml
title クラス図

class Player {
    -int[][] currentPosition
    +procPlayer()
    +P_getPositionOfPl()
}
class Labyrinth {
    -int     ID
    -int[2]  cordinateOfGoal
    -int[][] mapOfLabyrinth
    -int[][] revealedMpOfLabyrinth
    
    +isWallorWay()
    +revealMap()
    +getRevealedMap()
    +isPlayerOnGoal()
}
class LabsInfo {
    -LabyrinthType* labsList[NUMOFLAB]
    -static int     labIDOFPlayingLab
    +setLabyrinth()
    +getArrayOfLab()
    +isLabExist()
}

class Message {
    +String congratuation
    +String endGame
    +String startGame
    +String Title
    +String onGamging
}
class Time {
    -int startTime
    +setStartTime()
    +calcPlayTime()
}

LabsInfo *-- Labyrinth  


@enduml
