@startuml

package "input" {
     [ReadKey.h]
}

package "output" {
    [ShowView.h]
}

package "process" {
    [eventManager.h]
    [Timer.h]
    package "labyrinth" {
        [LabyrinthManager.h] --> [LabyrinthCfg.h]
        [LabyrinthCfg.h] --> [Labyrinth.h]
    }
    package "player" {
        [PlayerManager.h] --> [PlayerCfg.h] 
        [PlayerCfg.h] --> [Player.h]
    }
    
    package "communication" {
        [ComM.h] --> [IOCfg.h]
        [IOCfg.h] --> [IOType.h]
    }

    [eventManager.h] --> [Timer.h]
    [eventManager.h] -->  [PlayerManager.h]
    [eventManager.h] -->  [LabyrinthManager.h]
    [eventManager.h] -->  [ComM.h]
    
    
}


[ComM.h] --> [ReadKey.h]
[ComM.h] --> [ShowView.h]   






@enduml