@startuml
package "abstractIO" {
    [IOManager]
}

package "input" {
     [ReadKey]
}

[IOManager] --> [ReadKey]

package "process" {
    [eventManager]
    [Timer]
    [LabyrinthManager] --> [Labyrinth]
    [PlayerManager] --> [Player]
    [ComM]
}

package "output" {
    [IOManager] --> [ShowView]
}


[ComM]      --> [IOManager]     

[eventManager] --> [Timer]
[eventManager] -->  [PlayerManager]
[eventManager] -->  [LabyrinthManager]
[eventManager] -->  [ComM]




@enduml