@startuml
package "abstractIO" {
    [IOManager]
}

package "input" {
     [readKey]
}

[IOManager] --> [readKey]

package "process" {
    [eventManager]
    [timer]
    [labyrinthManager]
    [playerManager]
    [viewChanger]
}

package "output" {
    [IOManager] --> [showView]
}

[eventManager]     -->  [IOManager]


[viewChanger]      --> [IOManager]     

[eventManager] --> [timer]
[eventManager] -->  [playerManager]
[eventManager] -->  [labyrinthManager]
[eventManager] -->  [viewChanger]


@enduml