@startuml

title 迷路ゲームプレイ中シーケンス

loop
    eventManger -> UserOperation : waitInput()
    alt you got any kind of key input
        UserOperation -> readKey : getInput()
        readKey --> UserOperation
    end
    UserOperation --> eventManger

    eventManger -> playerManager : P_getPositionOfPl()
    playerManager --> eventManger

    eventManger -> labyrinthManager : revealLab()
    labyrinthManager --> eventManger

    alt not pass labyrinth
        eventManger -> ComM : procGame()
            ComM -> UserOperation : showPlayintLabyrinth()
                UserOperation -> showView : writeLabandPl()
                showView --> UserOperation
            UserOperation -> ComM
        ComM --> eventManger
    else pass labyrinth
        eventManger -> timer : calcPlayTime()
        timer --> eventManger 
        eventManger -> ComM : ProcAfterPassGame()
            ComM -> UserOperation : showPassView()
                UserOperation -> showView : writeCongandTime()
        break
        end
    end
end

@enduml