@startuml

title 迷路ゲームプレイ中シーケンス

loop
    eventManger -> IOManager : waitInput()
    alt you got any kind of key input
        IOManager -> readKey : getInput()
        readKey --> IOManager
    end
    IOManager --> eventManger

    eventManger -> playerManager : getPositionOfPl()
    playerManager --> eventManger

    eventManger -> labyrinthManager : revealLab()
    labyrinthManager --> eventManger

    alt not pass labyrinth
        eventManger -> viewChanger : procGame()
            viewChanger -> IOManager : showGameView()
                IOManager -> showView : writeLabandPl()
                showView --> IOManager
            IOManager -> viewChanger
        viewChanger --> eventManger
    else pass labyrinth
        eventManger -> timer : calcPlayTime()
        timer --> eventManger 
        eventManger -> viewChanger : ProcAfterPassGame()
            viewChanger -> IOManager : showPassView()
                IOManager -> showView : writeCongandTime()
        break
        end
    end
end

@enduml