@@startuml

title ゲームクリア後にタイトル画面に戻るまで

eventManager -> UserOperation : waitInput()
    alt you got any kind of key input
        UserOperation -> readKey : getInput()
        readKey --> UserOperation
    end
UserOperation --> eventManager

eventManager -> ComM : backToTitle()
    ComM -> UserOperation : showTitle()
        UserOperation -> showView : writeTitle()
        showView --> UserOperation
    UserOperation --> ComM
ComM --> eventManager

@@enduml