@startuml

title タイトル画面からの遷移

eventManager -> IOManager : waitInput()
    alt you got any kind of key input
        IOManager -> readKey : getInput()
        readKey --> IOManager
    end
IOManager --> eventManager

alt finish game
    eventManager -> ComM : finishGame()
        ComM -> IOManager : showFinishView()
            IOManager -> showView : writeFinishMessage()
            showView --> IOManager
        IOManager --> ComM
    ComM --> eventManager
    eventManager -> eventManager : endMyself()
    break
        note right
            end main loop
        end note
    end

else start game
    eventManager -> labyrinthManager : setLabyrinth()
    labyrinthManager --> eventManager
    
    eventManager -> playerManager : setPlayer()
    playerManager -->eventManager

    eventManager -> timer : getTime()
    timer --> eventManager

    eventManager -> ComM : playGame()
        ComM -> IOManager : showGameView()
            IOManager -> showView : writeLabandPl()
            showView --> IOManager
        IOManager --> ComM
    ComM --> eventManager

    note right
        ゲームシーケンスへ
    end note

end


@enduml