@startuml
title title
[*] --> Title

Title --> finishGame
Title --> playGame : Labyrinth

playGame --> ProcAfterPassGame : get to a goal
ProcAfterPassGame --> Title

finishGame -> [*]



Title :Labyrinth..*
Title : finish Game

playGame : Labyrinth
playGame : player

ProcAfterPassGame : time


@enduml